name: Build Phira

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ANDROID_HOME: ${{github.workspace}}/android-sdk
  ANDROID_NDK_HOME: ${{github.workspace}}/android-ndk-r27c
  ANDROID_NDK_ROOT: ${{github.workspace}}/android-ndk-r27c

jobs:
  Androidv8a:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config build-essential
      - name: Install Prpr-avc static-lib
        run: |
          wget https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip
          unzip prpr-avc.zip -d ./
      - name: Install Android Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "build-tools;33.0.2" "platforms;android-35"
          wget https://googledownloads.cn/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip -d ${{github.workspace}}
          cargo install cargo-ndk
      - name: Install Rust Toolchains
        uses: crusty-pie/toolchain@v1.0.8
        with:
          targets: aarch64-linux-android
      - name: Build
        run: |
          cd phira
          cargo ndk -t arm64-v8a -p 35 build --release --features "video chat"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build-v8a
          path: |
            target/aarch64-linux-android/release/libphira.so
  Androidv7a:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config build-essential
      - name: Install Prpr-avc static-lib
        run: |
          wget https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip
          unzip prpr-avc.zip -d ./
      - name: Install Android Tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "build-tools;33.0.2" "platforms;android-35"
          wget https://googledownloads.cn/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip -d ${{github.workspace}}
          cargo install cargo-ndk
      - name: Install Rust Toolchains
        uses: crusty-pie/toolchain@v1.0.8
        with:
          targets: armv7-linux-androideabi
      - name: Build
        run: |
          cd phira
          cargo ndk -t armeabi-v7a -p 35 build --release --features "video chat"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build-v7a
          path: |
            target/armv7-linux-androideabi/release/libphira.so
  Windowsx64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config
      - name: Install Prpr-avc static-lib
        run: |
          wget https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip
          unzip prpr-avc.zip -d ./
      - name: Install Rust Toolchains
        uses: crusty-pie/toolchain@v1.0.8
        with:
          targets: x86_64-pc-windows-gnu
      - name: Install MinGW Toolchain
        run: |
          sudo apt-get install -y mingw-w64
          wget https://github.com/madler/zlib/archive/refs/heads/develop.zip
          unzip develop.zip
          cd zlib-develop
          CHOST=x86_64-w64-mingw32 ./configure --static --prefix=/usr/x86_64-w64-mingw32
          make
          sudo make install
      - name: Build
        run: |
          cargo build --release --features "video chat" --bin phira-main --target x86_64-pc-windows-gnu
          cp target/x86_64-pc-windows-gnu/release/phira-main.exe phira-main.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x86_64
          path: |
            phira-main.exe
            assets
  Windowsx86:
    runs-on: ubuntu-22.04
    container:
      image: msys2/msys2:latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install MinGW Toolchain
        run: |
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm && pacman -Syu --noconfirm
          pacman -S --needed --noconfirm wget unzip base-devel git mingw-w64-toolchain
      - name: Install Prpr-avc static-lib
        run: |
          wget https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip
          unzip prpr-avc.zip -d ./
      - name: Install Rust Toolchains
        uses: crusty-pie/toolchain@v1.0.8
        with:
          targets: i686-pc-windows-gnu
      - name: Build
        run: |
          cargo build --release --features "video chat" --bin phira-main --target i686-pc-windows-gnu
          cp target/i686-pc-windows-gnu/release/phira-main.exe phira-main.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x86
          path: |
            phira-main.exe
            assets
  Linux64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config build-essential build-essential
      - name: Install Prpr-avc static-lib
        run: |
          wget https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip
          unzip prpr-avc.zip -d ./
      - name: Install Rust Toolchains
        uses: crusty-pie/toolchain@v1.0.8
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Build
        run: |
          cargo build --release --features "video chat" --bin phira-main --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/phira-main phira-main-t
          cp phira-main-t/phira-main phira-main
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-x64
          path: |
            phira-main
            assets