name: Build Phira

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ANDROID_HOME: ${{github.workspace}}/android-sdk
  ANDROID_NDK_HOME: ${{github.workspace}}/android-ndk-r27c
  ANDROID_NDK_ROOT: ${{github.workspace}}/android-ndk-r27c

jobs:
  Androidv8a:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare Build Environment
        uses: .github/workflows/PrepareBuild.yml
        with:
          targetPlatform: aarch64-linux-android
      - name: Build
        run: |
          cd phira
          cargo ndk -t arm64-v8a -p 35 build --release --features "video chat"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build-v8a
          path: |
            target/aarch64-linux-android/release/libphira.so
  Androidv7a:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare Build Environment
        uses: .github/workflows/PrepareBuild.yml
        with:
          targetPlatform: armv7-linux-androideabi
      - name: Build
        run: |
          cd phira
          cargo ndk -t arm64-v7a -p 35 build --release --features "video chat"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build-v7a
          path: |
            target/armv7-linux-androideabi/release/libphira.so
  Windowsx64:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare Build Environment
        uses: .github/workflows/PrepareBuild.yml
        with:
          targetPlatform: x86_64-pc-windows-gnu
      - name: Build
        run: |
          cargo build --release --features "video chat" --bin phira-main
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x86_64
          path: |
            target/x86_64-pc-windows-gnu/release/phira-main.exe
            assets
  Windowsx86:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare Build Environment
        uses: .github/workflows/PrepareBuild.yml
        with:
          targetPlatform: i686-pc-windows-gnu
      - name: Build
        run: |
          cargo build --release --features "video chat" --bin phira-main
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x86
          path: |
            target/i686-pc-windows-gnu/release/phira-main.exe
            assets
  Linux64:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare Build Environment
        uses: .github/workflows/PrepareBuild.yml
        with:
          targetPlatform: x86_64-unknown-linux-gnu
      - name: Build
        run: |
          cargo build --release --features "video chat" --bin phira-main
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-x64
          path: |
            target/x86_64-unknown-linux-gnu/release/phira-main
            assets